// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txwuggtasicwavdynllk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4d3VnZ3Rhc2ljd2F2ZHlubGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzEwNDUsImV4cCI6MjA2NTMwNzA0NX0.2DkVDw1T7oKCtsxHtCZvnb9E6uUlnmt1iAqwTRBFiIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);